services:
  forgejo:
    image: codeberg.org/forgejo/forgejo:${FORGEJO_VERSION}
    container_name: forgejo
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add:
      - SETUID
      - SETGID
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - apps
    volumes:
      - ./data:/data
    #  - ./config:/etc/gitea
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    ports:
      - "${FORGEJO_SSH_PORT}:2222"
    environment:
      USER_UID: ${USER_UID}
      USER_GID: ${USER_GID}
      FORGEJO__server__DOMAIN: ${FORGEJO_DOMAIN}
      FORGEJO__server__SSH_DOMAIN: ${FORGEJO_DOMAIN}
      FORGEJO__server__ROOT_URL: "https://${FORGEJO_DOMAIN}/"
      FORGEJO__server__HTTP_PORT: "3000"
      FORGEJO__server__PROTOCOL: "http"
      FORGEJO__server__START_SSH_SERVER: "true"
      FORGEJO__server__SSH_PORT: ${FORGEJO_SSH_PORT}
      FORGEJO__server__SSH_LISTEN_PORT: "2222"
      FORGEJO__database__DB_TYPE: "sqlite3"
      FORGEJO__service__DISABLE_REGISTRATION: "true"
      FORGEJO__security__INSTALL_LOCK: "true"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.forgejo.rule=Host(`${FORGEJO_DOMAIN}`)"
      - "traefik.http.routers.forgejo.entrypoints=websecure"
      - "traefik.http.routers.forgejo.tls=true"
      - "traefik.http.services.forgejo.loadbalancer.server.port=3000"
      - "traefik.docker.network=apps"
networks:
  apps:
    external: true
