services:
  uptime-kuma:
    image: louislam/uptime-kuma:2.3.2
    container_name: uptime-kuma
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    environment:
      TZ: ${TZ}
    volumes:
      - ./data:/app/data
    networks:
      - proxy
      - edge
      - apps
      - obs
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.uptime-kuma.rule=Host(`uptimekuma.home.lan`)"
      - "traefik.http.routers.uptime-kuma.entrypoints=websecure"
      - "traefik.http.routers.uptime-kuma.tls=true"
      - "traefik.http.routers.uptime-kuma.middlewares=authelia@docker"
      - "traefik.http.services.uptime-kuma.loadbalancer.server.port=3001"
      - "traefik.docker.network=obs"
networks:
  proxy:
    external: true
  edge:
    external: true
  apps:
    external: true
  obs:
    external: true
