[Interface]
Address = 10.13.13.1/24
ListenPort = 51820
PostUp = wg set %i private-key /etc/wireguard/server.key
PostUp = wg set %i peer ePkhwTqm89Y2k+HG/n+amY0zwOX42VqZs2kmKIQ8d1k= preshared-key /etc/wireguard/phone.psk
PostUp = wg set %i peer tzj7e9x66qr1TO0CuPA3hhxN68nFUOO9oxyXUzAh1xE= preshared-key /etc/wireguard/laptop.psk
# Keep peers off the LAN
PostUp = iptables -I FORWARD -i %i -o eth0 -j DROP
PreDown = iptables -D FORWARD -i %i -o eth0 -j DROP

[Peer]
# iphone
PublicKey = ePkhwTqm89Y2k+HG/n+amY0zwOX42VqZs2kmKIQ8d1k=
AllowedIPs = 10.13.13.3/32

[Peer]
# laptop
PublicKey = tzj7e9x66qr1TO0CuPA3hhxN68nFUOO9oxyXUzAh1xE=
AllowedIPs = 10.13.13.2/32
